---
- name: Pre-install | Merge user server config data with default
  set_fact:
    prometheus: "{{ prometheus_server_data | combine(prometheus_server_config, recursive=True) }}"
  tags:
    - always

- name: Pre-install | Merge user clients config data with default
  set_fact:
    prometheus_client: "{{ prometheus_clients_data | combine(prometheus_clients_config, recursive=True) }}"
  tags:
    - always

# Overall idea behind this is to get all hosts of this playbook (look at
# https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html)
# and then get port based on current host position in list of all these hosts.
- name: Pre-install | Initialize autossh port number
  set_fact:
    autossh_port_number: "{{ prometheus_client.exporters_autossh_to_prometheus.initial_port + prometheus_client.exporters_autossh_to_prometheus.multiplier * item.0 }}"
  with_indexed_items: "{{ ansible_play_hosts_all }}"
  when: item.1 == inventory_hostname

- name: Show initial autossh port number for current host
  debug:
    msg: "Autossh initial port number for host {{ inventory_hostname }} is {{ autossh_port_number }}"
    verbosity: 1

- name: Show prometheus pre-flight config
  debug:
    var: prometheus
    verbosity: 1

- name: Include preinstallation tasks
  import_tasks: prometheus_common/preinstall.yml
  tags:
    - preinstall
    - prometheus_clients
    - prometheus_server

- name: Include exporters tasks
  import_tasks: prometheus_clients/exporters.yml
  tags:
    - prometheus
    - prometheus_clients
    - exporters

- name: Include exporters reverse proxy tasks
  import_tasks: prometheus_clients/exporters_reverse_proxy.yml
  when: prometheus_client.exporters_reverse_proxy.enabled
  tags:
    - prometheus
    - prometheus_clients
    - exporters
    - reverse_proxy
    - proxy

- name: Show prometheus flight config
  debug:
    var: prometheus
    verbosity: 1

- name: Include timescale DB tasks
  import_tasks: prometheus_server/timescale.yml
  when: prometheus.prometheus.install_server and prometheus.timescale.enabled
  tags:
    - timescale
    - postgres
    - storage
    - prometheus_server
    - prometheus

- name: Include victoriametrics DB tasks
  import_tasks: prometheus_server/victoriametrics.yml
  when: prometheus.prometheus.install_server and prometheus.victoriametrics.enabled
  tags:
    - victoriametrics
    - storage
    - prometheus_server
    - prometheus

- name: Include prometheus tasks
  import_tasks: prometheus_server/prometheus.yml
  when: prometheus.prometheus.install_server
  tags:
    - prometheus
    - prometheus_server

- name: Include alertmanager tasks
  import_tasks: prometheus_server/alertmanager.yml
  when: prometheus.alertmanager.enabled
  tags:
    - prometheus_server
    - prometheus
    - alertmanager
