---
- name: Create scrape config var for blackbox exporter
  set_fact:
    blackbox_job_config:
      job_name: "{{ ansible_host }}_blackbox_{{ item.config_name }}"
      honor_labels: false
      metrics_path: "/{{ prometheus_client.exporters.blackbox_exporter.metrics_path }}"
      params: "{{ item.scrape_params }}"
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: "127.0.0.1:{{ autossh_port_number }}"
      static_configs:
        - targets: "{{ item.scrape_targets }}"
          labels:
            scrape_type: "blackbox_exporter"
            node_name: "{{ ansible_host }}"
  tags:
    - prometheus_clients
    - exporters
    - blackbox_exporter
    - server_config
    - prometheus_config

- name: Add scrape config var for blackbox exporter to the jobs list
  set_fact:
    blackbox_jobs_config: "{{ blackbox_jobs_config|default([]) + [ blackbox_job_config ] }}"
  tags:
    - prometheus_clients
    - exporters
    - blackbox_exporter
    - server_config
    - prometheus_config


