---
groups:
  - name: Mysqld.rules
    rules:
    - alert: MysqlDown
      expr: mysql_up == 0
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "MySQL down (instance {{ $labels.node_name }})"
        description: "MySQL instance is down on {{ $labels.node_name }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: MysqlTooManyConnections
      expr: avg by (instance) (max_over_time(mysql_global_status_threads_connected[5m])) / avg by (instance) (mysql_global_variables_max_connections) * 100 > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "MySQL too many connections (instance {{ $labels.node_name }})"
        description: "More than 80% of MySQL connections are in use on {{ $labels.node_name }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: MysqlHighThreadsRunning
      expr: avg by (instance) (max_over_time(mysql_global_status_threads_running[5m])) / avg by (instance) (mysql_global_variables_max_connections) * 100 > 60
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "MySQL high threads running (instance {{ $labels.node_name }})"
        description: "More than 60% of MySQL connections are in running state on {{ $labels.node_name }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: MysqlSlaveIoThreadNotRunning
      expr: mysql_slave_status_master_server_id > 0 and ON (instance) mysql_slave_status_slave_io_running == 0
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "MySQL Slave IO thread not running (instance {{ $labels.node_name }})"
        description: "MySQL Slave IO thread not running on {{ $labels.node_name }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: MysqlSlaveSqlThreadNotRunning
      expr: mysql_slave_status_master_server_id > 0 and ON (instance) mysql_slave_status_slave_sql_running == 0
      for: 5m
      labels:
        severity: error
      annotations:
        summary: "MySQL Slave SQL thread not running (instance {{ $labels.node_name }})"
        description: "MySQL Slave SQL thread not running on {{ $labels.node_name }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: MysqlRestarted
      expr: mysql_global_status_uptime < 60
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "MySQL restarted (instance {{ $labels.node_name }})"
        description: "MySQL has just been restarted, less than one minute ago on {{ $labels.node_name }}.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
