---
- name: Exporters | Start docker node exporter container
  docker_service:
    state: present
    project_name: prometheus_node_exporter
    definition:
      version: '2'
      services:
        node_exporter:
          image: "{{ prometheus.exporters.node_exporter.docker_image }}"
          container_name: "{{ prometheus.exporters.node_exporter.container_name }}"
          ports:
            - "127.0.0.1:{{ prometheus.exporters.node_exporter.host_port }}:9100"
          hostname: "{{ ansible_host }}"
          restart: always
          labels: "{{ prometheus.exporters.node_exporter.docker_labels }}"
      networks:
        default:
          external:
            name: "{{ prometheus.docker.network_name }}"
